Feat runtime varibale v3
devtron-labs/devtron-services pull request #60
Opened 2024-11-25 13:53 UTC by Ash-exp

2024-11-28 09:03 UTC, kartik-579 requested changes

2024-11-28 09:03 UTC, kartik-579 commented on common-lib/ci-runner/bean/bean.go
we have moved a lot of structs and I think the only thing common in ci-runner and orchestrator is wfRequest struct. If you want to keep the wfRequest structs here I suggest we can keep the package named after workflow and ensure it should not contain any thing which is specific to orchestrator or ci-runner internal logics and is not subject to change w.r.t them

2024-12-04 10:54 UTC, nishant-d approved these changes

2024-12-16 14:05 UTC, nishant-d approved these changes

2024-12-16 14:21 UTC, merged